---
output: github_document
editor_options: 
  chunk_output_type: console
---
# DOM Composition Wheel - Associated Code & Composition Wheel Template  

*Aukes PJK and Schiff SL. 2020. Composition Wheels: Visualizing dissolved organic matter using common composition metrics across a variety of Canadian Ecozones. bioRxiv TBD doi: TBD*

This repository contains all the code to create the figures in the manuscript, as well as a template to create your own Composition Wheels.  

Metadata can be found and hosted by Wilfrid Laurier University Dataverse.

# Files Found Here

## 'DOM Comp Wheel - R Code.md'

This contains all the R code to run the statistical analysis and create the figures found in the manuscript. Data can be downloaded from the WLU Dataverse.

## 'Composition Wheel Template.md'

An RMarkdown document that contains all the code to create your own Composition Wheel. Included is a sample dataset ('test_dataset.csv') to see how the dataframe is laid out and works with the code.

# Contact
If you have any further questions or comments, I'd be happy to hear from you. You can reach me at:  
paukes@wlu.ca